SQL> 
SQL> 
 
SQL> CREATE TABLE CUSTOMER
  2  (
  3  CUSTOMERID NUMBER(10) PRIMARY KEY,
  4  CUSTOMERNAME VARCHAR(30) NOT NULL,
  5  EMAIL VARCHAR(40) UNIQUE,
  6  PHONENUMBER NUMBER(10) UNIQUE NOT NULL
  7  )
  8  ;

Table created.

SQL> CREATE TABLE PRODUCT
  2  (
  3  PRODUCTID NUMBER(10) PRIMARY KEY,
  4  PNAME VARCHAR(20) NOT NULL,
  5  PRICE NUMBER(10,5),
  6  AVAILABLE NUMBER(5)
  7  );

Table created.

SQL> 
SQL> 
SQL> 

SQL> CREATE TABLE ORDERS
  2  (
  3  ORDER_ID VARCHAR(30) PRIMARY KEY,
  4  ORDER_DATE DATE,
  5  CUSTOMERID NUMBER(10), FOREIGN KEY (CUSTOMERID)
  6  			REFERENCES CUSTOMER (CUSTOMERID),
  7  PRODUCTID NUMBER(10), FOREIGN KEY (PRODUCTID)
  8  			REFERENCES PRODUCT (PRODUCTID)
  9  );

Table created.

SQL> CREATE TABLE SHIPPING
  2  (
  3  SHIPPING_ID NUMBER(10) PRIMARY KEY,
  4  DELIVERY_DATE DATE,
  5  STATUS VARCHAR(20),
  6  ORDER_ID VARCHAR(30), FOREIGN KEY (ORDER_ID)
  7  			REFERENCES ORDERS (ORDER_ID)
  8  );

Table created.

SQL> SPOOL OFF
